# Generated by Django 5.2.7 on 2025-10-29 08:43

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('region', models.IntegerField(choices=[(1, 'Miền Bắc'), (2, 'Miền Trung'), (3, 'Miền Nam')])),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sea', 'Biển'), ('mountain', 'Núi'), ('resort', 'Nghỉ dưỡng'), ('adventure', 'Khám phá'), ('cultural', 'Văn hoá'), ('history', 'Lịch sử')], max_length=30), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='agencies.agency')),
            ],
            options={
                'db_table': 'tours_tour',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='tours_tour_name_836ef1_idx'), models.Index(fields=['price'], name='tours_tour_price_674fc5_idx'), models.Index(fields=['region'], name='tours_tour_region_d618d8_idx'), models.Index(fields=['created_at'], name='tours_tour_created_3044fa_idx'), models.Index(fields=['categories'], name='tours_tour_categor_61329c_idx')],
            },
        ),
    ]
