# Generated by Django 5.2.7 on 2025-10-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='provider',
            new_name='agency',
        ),
    ]
