# Generated by Django 5.2.7 on 2025-11-04 08:57

import apps.tours.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.tours.models.tour_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'db_table': 'tours_tour_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
