# Generated by Django 5.2.7 on 2025-11-06 09:30

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_avatar_agency_description_agency_license_file'),
        ('tours', '0002_tourimage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tour',
            name='tours_tour_categor_61329c_idx',
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='pickup_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tour',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='services_excluded',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='services_included',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='transportation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['categories'], name='tour_categories_gin'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['itinerary'], name='tour_itinerary_gin'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=django.contrib.postgres.indexes.GinIndex(fields=['policy'], name='tour_policy_gin'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.CheckConstraint(condition=models.Q(('discount_price__isnull', True), ('discount_price__lte', models.F('price')), _connector='OR'), name='discount_lte_price'),
        ),
    ]
