# Generated by Django 5.2.7 on 2025-10-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_rename_address_agency_address_agency_and_more'),
        ('tours', '0002_rename_provider_tour_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='agencies.agency'),
        ),
    ]
