# Generated by Django 5.2.7 on 2025-11-08 15:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_rename_company_name_agency_agency_name'),
        ('tours', '0003_remove_tour_tours_tour_categor_61329c_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.UniqueConstraint(models.F('agency'), django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('start_location'), django.db.models.functions.text.Lower('end_location'), models.F('duration_days'), name='uniq_tour_agency_name_route_days_ci'),
        ),
    ]
