# Generated by Django 5.2.7 on 2025-11-16 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_rename_company_name_agency_agency_name'),
        ('tours', '0004_tour_uniq_tour_agency_name_route_days_ci'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tour',
            name='discount_lte_price',
        ),
        migrations.RemoveIndex(
            model_name='tour',
            name='tours_tour_price_674fc5_idx',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AddField(
            model_name='tour',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='children_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giảm giá theo phần trăm (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['adult_price'], name='tours_tour_adult_p_1c4315_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['children_price'], name='tours_tour_childre_da9fe3_idx'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.CheckConstraint(condition=models.Q(('discount__isnull', True), ('discount__gte', 0), _connector='OR'), name='discount_gte_zero'),
        ),
    ]
