# Generated by Django 5.2.7 on 2025-10-21 07:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_rename_address_agency_address_agency_and_more'),
        ('tours', '0004_tour_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sea', 'Biển'), ('mountain', 'Núi'), ('resort', 'Nghỉ dưỡng'), ('adventure', 'Khám phá'), ('cultural', 'Văn hoá'), ('history', 'Lịch sử')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.IntegerField(choices=[(1, 'Miền Bắc'), (2, 'Miền Trung'), (3, 'Miền Nam')], default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['region'], name='tours_tour_region_d618d8_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['created_at'], name='tours_tour_created_3044fa_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['categories'], name='tours_tour_categor_61329c_idx'),
        ),
    ]
