# Generated by Django 5.2.7 on 2025-12-16 18:41

import apps.tours.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_remove_agency_uniq_agency_legal_id_not_null_and_more'),
        ('tours', '0005_remove_tour_discount_lte_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourThumbnail',
            fields=[
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thumbnail', serialize=False, to='tours.tour')),
                ('thumbnail', models.ImageField(upload_to=apps.tours.models.tour_thumbnail_upload_to)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tours_tour_thumbnail',
            },
        ),
        migrations.RemoveConstraint(
            model_name='tour',
            name='uniq_tour_agency_name_route_days_ci',
        ),
        migrations.RemoveConstraint(
            model_name='tour',
            name='discount_gte_zero',
        ),
        migrations.RemoveIndex(
            model_name='tour',
            name='tour_itinerary_gin',
        ),
        migrations.RemoveIndex(
            model_name='tour',
            name='tour_policy_gin',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='pickup_points',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_location',
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['departure_location'], name='tours_tour_departu_dd2aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['destination'], name='tours_tour_destina_ea8ef4_idx'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.CheckConstraint(condition=models.Q(('discount__isnull', True), models.Q(('discount__gte', 0), ('discount__lte', 100)), _connector='OR'), name='discount_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.UniqueConstraint(fields=('agency', 'name', 'departure_location', 'destination', 'duration_days'), name='uniq_tour_agency_name_depart_dest_days'),
        ),
    ]
