# Generated by Django 5.2.7 on 2025-12-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tourthumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='guide',
        ),
    ]
