# Generated by Django 5.2.7 on 2025-10-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount',
            new_name='total_price',
        ),
    ]
