# Generated by Django 5.2.7 on 2026-01-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ đại lý xác nhận'), ('paid_waiting', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('rejected', 'Từ chối / Hủy')], default='pending', max_length=20),
        ),
    ]
