# Generated by Django 5.2.7 on 2025-10-17 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Service Provider'), (3, 'Admin')]), blank=True, default=[1], size=None),
        ),
    ]
