# Generated by Django 5.2.7 on 2025-10-18 17:13

import apps.users.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Service Provider'), (3, 'Admin')]), blank=True, default=apps.users.models.default_customer_role, size=None),
        ),
    ]
