# Generated by Django 5.2.7 on 2025-10-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_address_agency_email_agency_hotline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='address',
            new_name='address_agency',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='email',
            new_name='email_agency',
        ),
    ]
