# Generated by Django 5.2.7 on 2025-11-06 03:40

import apps.agencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.agencies.models.agency_avatar_upload_to, validators=[apps.agencies.models.validate_avatar]),
        ),
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.agencies.models.agency_license_upload_to, validators=[apps.agencies.models.validate_license]),
        ),
    ]
