# Generated by Django 5.2.7 on 2025-11-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_avatar_agency_description_agency_license_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='company_name',
            new_name='agency_name',
        ),
    ]
