# Generated by Django 5.2.7 on 2025-10-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_rename_address_agency_address_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
