# Generated by Django 5.2.7 on 2025-12-14 08:50

import apps.agencies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_rename_company_name_agency_agency_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual')], default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='legal_id_back',
            field=models.ImageField(blank=True, null=True, upload_to=apps.agencies.models.agency_legal_id_upload_to, validators=[apps.agencies.models.validate_legal_id]),
        ),
        migrations.AddField(
            model_name='agency',
            name='legal_id_front',
            field=models.ImageField(blank=True, null=True, upload_to=apps.agencies.models.agency_legal_id_upload_to, validators=[apps.agencies.models.validate_legal_id]),
        ),
        migrations.AddField(
            model_name='agency',
            name='legal_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='legal_representative_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_code__isnull', False)), fields=('tax_code',), name='uniq_agency_tax_code_not_null'),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(condition=models.Q(('legal_id_number__isnull', False)), fields=('legal_id_number',), name='uniq_agency_legal_id_not_null'),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(condition=models.Q(('email_agency__isnull', False)), fields=('email_agency',), name='uniq_agency_email_not_null'),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(condition=models.Q(('hotline__isnull', False)), fields=('hotline',), name='uniq_agency_hotline_not_null'),
        ),
    ]
