# Generated by Django 5.2.7 on 2025-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_agency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='reason_rejected',
            field=models.TextField(blank=True, null=True),
        ),
    ]
