# Generated by Django 5.2.7 on 2025-12-14 12:58

import apps.agencies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agency_agency_type_agency_bank_account_holder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agency',
            name='uniq_agency_legal_id_not_null',
        ),
        migrations.AlterField(
            model_name='agency',
            name='bank_account_holder',
            field=models.CharField(default='__TEMP__', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='bank_account_number',
            field=models.CharField(default='__TEMP__', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='bank_name',
            field=models.CharField(default='__TEMP__', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='legal_id_back',
            field=models.ImageField(default='__TEMP__', upload_to=apps.agencies.models.agency_legal_id_upload_to, validators=[apps.agencies.models.validate_legal_id]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='legal_id_front',
            field=models.ImageField(default='__TEMP__', upload_to=apps.agencies.models.agency_legal_id_upload_to, validators=[apps.agencies.models.validate_legal_id]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='legal_id_number',
            field=models.CharField(default='__TEMP__', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='legal_representative_name',
            field=models.CharField(default='__TEMP__', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('legal_id_number',), name='uniq_agency_legal_id_number'),
        ),
    ]
